import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import "./Shogakukanjcv3.css"
import "./thesaurus.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Next Japanese Dictionary",
  description: "Generated by licmucm@gmail.com",
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
